

const gifts = [
    { name: "Instrumento musical para niños", relacion: ["Familiar"], edad: { min: 0, max: 5 }, gustos: ["Musica"] },
    { name: "Tablet educativa", relacion: ["Familiar"], edad: { min: 0, max: 5 }, gustos: ["Tecnologia"] },
    { name: "Bateria", relacion: ["Familiar", "Amigo", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Musica"] },
    { name: "Pelota", relacion: ["Familiar", "Pareja", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Juegos"] },
    { name: "Bate de Beisbol", relacion: ["Familiar", "Pareja", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 12 }, gustos: ["Juegos"] },
    { name: "Oso de peluche", relacion: ["Pareja"], edad: { min: 13, max: 18 }, gustos: ["Juegos"] },
    { name: "Bloques de juguete", relacion: ["Familiar", "Amigo"], edad: { min: 0, max: 5 }, gustos: ["Juegos"] },
    { name: "Bicicleta", relacion: ["Familiar"], edad: { min: 6, max: 12 }, gustos: ["Juegos"] },
    { name: "Guitarra", relacion: ["Familiar", "Pareja", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 12 }, gustos: ["Musica"] },
    { name: "Copa de vino", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Cocina"] },
    { name: "Taza", relacion: ["Familiar", "Pareja", "Amigo", "Compañero Laboral"], edad: { min: 12, max: 19 }, gustos: ["Cocina"] },
    { name: "Tabla de madera para cortar", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 12, max: 19 }, gustos: ["Cocina"] },
    { name: "Portaretrato digital", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Tecnologia", "Arte"] },
    { name: "Auriculares", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 13, max: 19 }, gustos: ["Tecnologia", "Musica"] },
    { name: "Consola de videojuegos", relacion: ["Familiar", "Amigo"], edad: { min: 6, max: 19 }, gustos: ["Tecnologia", "Juegos"] },
    { name: "Laptop", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 13, max: 19 }, gustos: ["Tecnologia"] },
    { name: "Celular", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 13, max: 19 }, gustos: ["Tecnologia"] },
    { name: "Valija", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 19 }, gustos: ["Viajes"] },
    { name: "Mochila", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 19 }, gustos: ["Viajes"] },
    { name: "Bolso", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Deportes", "Viajes"] },
    { name: "Rompecabezas", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 0, max: 19 }, gustos: ["Juegos"] },
    { name: "Juego de cuchillos", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 19, max: 19 }, gustos: ["Cocina"] },
    { name: "Microondas", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Cocina", "Tecnologia"] },
    { name: "Botella Térmica", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 13, max: 19 }, gustos: ["Deportes"] },
    { name: "Termo", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 13, max: 19 }, gustos: ["Cocina"] },
    { name: "Lentes de Sol", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Viajes"] },
    { name: "Juego de mate", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 13, max: 19 }, gustos: ["Cocina"] },
    { name: "Vendas", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 13, max: 19 }, gustos: ["Deportes"] },
    { name: "Parlante inalambrico", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 13, max: 19 }, gustos: ["Musica", "Tecnologia"] },
    { name: "Mazo de naipes", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 19 }, gustos: ["Juegos"] },
    { name: "Juego de mesa", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 19 }, gustos: ["Juegos"] },
    { name: "Libros Musicales Interactivos", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Musica"] },
    { name: "Peluche Musical", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Musica"] },
    { name: "Alfombra Musical", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Musica"] },
    { name: "Reloj Inteligente para Niños", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Tecnologi,a"] },
    { name: "Proyector de Luces Nocturnas", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Tecnologia"] },
    { name: "Libro de Actividades de Viaje", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Viajes"] },
    { name: "Kit de Arte Portátil", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Viajes"] },
    { name: "Libro de Recetas para Niños", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Cocina"] },
    { name: "Juego de Cocina de Juguete", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Cocina"] },
    { name: "Cortadores de Galletas Temáticos", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Cocina"] },
    { name: "Bicicleta sin pedales para niños", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Deportes"] },
    { name: "Set de raquetas de tenis de juguete", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Deportes"] },
    { name: "Juego de Bowling para niños", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 0, max: 5 }, gustos: ["Deportes"] },
    { name: "Rollers", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 12 }, gustos: ["Deportes"] },
    { name: "Cuerda para saltar de alta calidad", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 19 }, gustos: ["Deportes"] },
    { name: "Set de equipo de béisbol", relacion: ["Familiar", "Amigo", "Compañero Laboral"], edad: { min: 6, max: 12 }, gustos: ["Deportes"] },
    { name: "Estuche para instrumentos", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Musica"] },
    { name: "Karaoke con micrófono", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Musica"] },
    { name: "Lámpara con forma de nota musical", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Musica"] },
    { name: "Delantal Personalizado", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Cocina"] },
    { name: "Máquina para hacer helados caseros", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Cocina"] },
    { name: "Set de decoración de pasteles", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Cocina"] },
    { name: "Telescopio", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Tecnologia"] },
    { name: "Microscopio digital", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Tecnologia"] },
    { name: "Camara digital", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Tecnologia"] },
    { name: "Bajo", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Musica"] },
    { name: "Luces Led para habitación", relacion: ["Pareja"], edad: { min: 13, max: 18 }, gustos: ["Tecnologia"] },
    { name: "Funda de celular", relacion: ["Pareja"], edad: { min: 13, max: 18 }, gustos: ["Tecnologia"] },
    { name: "Kit de fotografia para Smartphone", relacion: ["Pareja"], edad: { min: 13, max: 18 }, gustos: ["Tecnologia"] },
    { name: "Cocina eléctrica portátil", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 19 }, gustos: ["Cocina", "Viajes"] },
    { name: "Pochoclera", relacion: ["Familiar", "Amigo", "Compañero Laboral", "Pareja"], edad: { min: 6, max: 12 }, gustos: ["Tecnologia", "Cocina"] },
    { name: "Tablas de quesos y embutidos", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Cocina"] },
    { name: "Cava", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Cocina", "Tecnologia"] },
    { name: "Vinilos de colección", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Musica"] },
    { name: "Proyector de Cine", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Tecnologia"] },
    { name: "Reloj deportivo inteligente", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Deportes"] },
    { name: "Auriculares Bluetooth con estuche de carga", relacion: ["Pareja"], edad: { min: 13, max: 18 }, gustos: ["Tecnologia"] },
    { name: "Juego de mesa para parejas", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Juegos"] },
    { name: "Videojuego cooperativo", relacion: ["Pareja"], edad: { min: 19, max: 19 }, gustos: ["Juegos"] },
    { name: "Lámpara de escritorio LED", relacion: ["Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Juegos"] },
    { name: "Toalla de microfibra deportiva", relacion: ["Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Deportes"] },
    { name: "Kit de condimentos gourmet", relacion: ["Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Cocina"] },
    { name: "Adaptador de corriente universal", relacion: ["Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Viajes"] },
    { name: "Juego de mesa estratégico", relacion: ["Compañero Laboral"], edad: { min: 19, max: 19 }, gustos: ["Juegos"] },
   
];
export default gifts;




